version: '3.5'
services:
  app:
    build:
      context: ../
      dockerfile: ./infra/Dockerfile.prod
    restart: always
    container_name: app_facebook_lite
    ports:
      - ${PORT}:${PORT}
    labels:
      "autoheal": "true"      
    healthcheck:
      test: 'curl --fail http://localhost:${PORT}/system/healthchec || exit 1'
      interval: 5s
      timeout: 3s
      retries: 2
    depends_on:
      db:
        condition: service_healthy
      test_app:
        condition: service_completed_successfully        
  
  test_app:
    build:
      context: ../
      dockerfile: ./infra/Dockerfile.test
    container_name: test_app_facebook_lite    
    depends_on:
      db:
        condition: service_healthy

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal_facebook_lite   
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'    
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal    
      - AUTOHEAL_START_PERIOD=30
      - AUTOHEAL_INTERVAL=10
      - CURL_TIMEOUT=10
    depends_on:
      app:
        condition: service_completed_successfully           

  db: # Banco de dados
    image: postgres
    restart: always
    container_name: db_facebook_lite
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - 5432:5432
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}']
      interval: 5s
      timeout: 3s
      retries: 5