export enum ExceptionsConstants {
  USERNAME_LARGE_64_LIMIT = 'exception:USERNAME_LARGE_64_LIMIT',
  ID_NOT_UUID = 'exception:ID_NOT_UUID',
  OWNER_NOT_UUID = 'exception:OWNER_NOT_UUID',
  EMAIL_NOT_VALID = 'exception:EMAIL_NOT_VALID',
  IMAGE_URL_NOT_VALID = 'exception:IMAGE_URL_NOT_VALID',
  TITLE_NOT_VALID = 'exception:TITLE_NOT_VALID',
  DESCRIPTION_NOT_VALID = 'exception:DESCRIPTION_NOT_VALID',
}
